# Generated by Django 3.2 on 2023-01-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20230123_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='is_limited',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ограниченный'),
        ),
    ]
