# Generated by Django 3.2 on 2023-01-26 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20230126_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributes',
            options={'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='description',
        ),
        migrations.AddField(
            model_name='sale',
            name='full_description',
            field=models.TextField(default='', verbose_name='Полное Описание'),
        ),
        migrations.AddField(
            model_name='sale',
            name='short_description',
            field=models.TextField(default='', verbose_name='Краткое описание'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
