# Generated by Django 3.2 on 2023-01-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
