# Generated by Django 3.2 on 2023-01-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_sale_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
    ]
