# Generated by Django 3.2 on 2023-01-30 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20230129_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='marks',
        ),
    ]
