# Generated by Django 3.2 on 2023-02-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='is_popular',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Популярный?'),
        ),
    ]
