# Generated by Django 3.2 on 2023-02-13 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_tags_is_popular'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тэги', 'verbose_name_plural': 'Тэг'},
        ),
    ]
