# Generated by Django 3.2 on 2023-02-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_tags_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_free_delivery',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='С бесплатной доставкой?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_limited',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ограниченный?'),
        ),
    ]
