# Generated by Django 4.1.4 on 2023-01-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(default='', max_length=50, verbose_name='Отчество'),
        ),
    ]
