version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn marketplace.wsgi:application --bind 0.0.0.0:8000
    restart: always
    image: localhost/marketplace
    container_name: marketplace_web

    volumes:
      - .:/home/app/web
      - ./staticfiles:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./staticfiles:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 8000:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: