# Generated by Django 4.1.4 on 2023-01-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер банковской карты'),
        ),
    ]
