# Generated by Django 3.2 on 2023-02-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20230124_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='code',
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Номер банковской карты'),
        ),
    ]
