# Generated by Django 3.2 on 2023-02-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20230201_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='code',
            field=models.CharField(default='', max_length=255, verbose_name='Код'),
        ),
    ]
