# Generated by Django 3.2 on 2023-02-09 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_payment_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='count',
        ),
    ]
